Enlistjob
VinhVTHE181750/mJOB pull request #29
Opened 2024-06-03 09:35 UTC by KhanhNQ-HE181237

2024-06-03 09:43 UTC, HE176788MaiNhatHoang approved these changes

2024-06-04 01:07 UTC, VinhVTHE181750 commented on backend/config/db.json
This file should be ignored.

2024-06-04 01:08 UTC, VinhVTHE181750 requested changes

2024-06-04 01:08 UTC, VinhVTHE181750 commented on backend/scripts/DB.sql
This file can't be removed.

2024-06-04 01:08 UTC, VinhVTHE181750 commented
Should branch from `main`, latest commit instead.

2024-06-04 01:08 UTC, closed without merging